language: go,node_js
dist: xenial
sudo: false
cache: yarn
git:
  depth: 1
branches:
  only:
    - master
notifications:
  email: false
matrix:
  include:
    - language: go
      go: 1.13.5
      before_install:
        - make deps-go
      script:
        - make build-linux-server-only
    - language: go
      go: 1.13.5
      before_install:
        - make deps-go
      script:
        - make build-mac-server-only
      - language: go
      go: 1.13.5
      before_install:
        - make deps-go
      script:
        - make build-windows-server-only
    - language: node_js
      node_js: 10.18.0
      before_install:
        - make deps-web
      script:
        - make build-web
